name: builkd & deploy spring app

on:
  push:
    branches:
      - main



jobs:
    build-deploy:
        name: build and deploy spring boot for beginner
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v3
          
          - name: set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'corretto'

          - name: Unit Tests
            run: mvn -B test --file pom.xml

          - name: Build with Maven
            run: |
              mvn clean
              mvn -B package --file pom.xml
